name: Run Tests on Implementation

on:
    push:
        branches: main
    pull_request:
        branches: main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: ğŸ“¥ Install dependencies
        run: |
            chmod +x setup.sh
            sudo ./setup.sh

      - name: âœ… Run tests
        run: |
            chmod +x check.sh
            ./check.sh 2>&1 | tee tests_results.txt
      
      - name: ğŸ–¼ï¸ Generate Images
        run: |
          chmod +x image-generator.sh
          ./image-generator.sh --all

      - name: ğŸ’¾ Upload test logs as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checker-logs
          path: |
            tests_results.txt
            # Without `*` globbing, folders files will not be uploaded
            tests-out/*
            images/*
          retention-days: 7